UIH-619: Move components to repo
CraftTurf/craftturf-react-workshop pull request #1
Opened 2017-01-29 20:35 UTC by kobomarun

2017-01-29 20:51 UTC, jabdul requested changes

2017-01-29 20:51 UTC, jabdul commented on package.json
> +  "private": true,
Why is this private? We should perhaps remove this.

2017-01-29 20:51 UTC, jabdul commented on src/App.test.js
> +});
There's no assertion in this test, so what's the purpose?
 I suggest add a meaningful test

2017-01-29 20:51 UTC, jabdul commented on src/components/Counter/Counter.jsx
> +    <button
Indent

2017-01-29 20:51 UTC, jabdul commented on src/components/Counter/Counter.jsx
> +import CounterStyles from './Counter.styles'
Rename `CounterStyles` to `styles`. 

Less verbose

2017-01-29 20:51 UTC, jabdul commented on src/components/Counter/Counter.jsx
> +  onClick: React.PropTypes.Func
What about `children`?

2017-01-29 20:51 UTC, jabdul commented on src/components/Counter/Counter.styles.jsx
> +    cursor: 'poiter',
`pointer`

2017-01-29 20:51 UTC, jabdul commented on src/components/Counter/MainCounter.jsx
> +      </Counter>
Indent

2017-01-29 20:56 UTC, jabdul commented on src/components/Counter/Counter.styles.jsx
> +    height: '40px',
By default, constant values are coerced into `px` units.

So
```css
height: '40px'
```

is same as...

```css
height: 40
```

2017-01-30 10:38 UTC, kobomarun commented on src/components/Counter/Counter.styles.jsx
> +    height: '40px',
This did not work with `px`

2017-01-30 18:26 UTC, merged